version: "3.7"

services:
  app_proxy:
    # Use the SERVICE NAME 'app' instead of the generated container name
    # This is more robust as container names can change.
    environment:
      APP_HOST: app 
      APP_PORT: 8998
    depends_on:
      - app

  app:
    # Remove the @sha256 hash to allow the Pi to find the ARM64 version
    image: ghcr.io/ardoviniandrea/viniplay:0.10.1
    platform: linux/arm64  # <--- Change this from amd64 to arm64
    # REMOVE the 'platform: linux/amd64' line entirely
    volumes:
      - ${APP_DATA_DIR}/data/app_data:/data
      - ${APP_DATA_DIR}/data/dvr:/dvr
    environment:
      SESSION_SECRET: ${APP_PASSWORD}
      VAPID_CONTACT_EMAIL: mailto:your_email@example.com