version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: grzegorz-ping-monitor_server_1
      APP_PORT: 4080

  server:
    # ZAMIAST sekcji build: używamy gotowego obrazu z GitHub
    image: ghcr.io/gk-ghub/grzegorz-ping-monitor:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - DATA_DIR=/data
      - PORT=4080