services:
  app_proxy:
    environment:
      APP_HOST: grzegorz-gitlab-runner_gitlab-runner_1
      APP_PORT: 9252
      PROXY_AUTH_ADD: "false"

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: on-failure
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      bash -c "
        mkdir -p /etc/gitlab-runner &&
        if [ ! -f /etc/gitlab-runner/config.toml ]; then
          printf 'concurrent = 4\ncheck_interval = 10\n' > /etc/gitlab-runner/config.toml;
        fi;
        exec gitlab-runner run --user=gitlab-runner --working-directory=/home/gitlab-runner
      "
